sentence:
  IEO: "It's eleven o'clock"
  TIE: "That is exactly what happened"
  IOM: "I'm on my way to the meeting"
  IWW: "I wonder what this is about"
  TAI: "The airplane is almost full"
  MTI: "Maybe tomorrow it will be cold"
  IWL: "I would like a new alarm clock"
  ITH: "I think I have a doctor's appointment"
  DFA: "Don't forget a jacket"
  ITS: "I think I've seen this before"
  TSI: "The surface is slick"
  WSI: "We'll stop in a couple of minutes"
emotion:
  ANG: "Anger"
  DIS: "Disgust"
  FEA: "Fear"
  HAP: "Happy/Joy"
  NEU: "Neutral"
  SAD: "Sad"
emotion_level:
  LO: "Low"
  MD: "Medium"
  HI: "High"
  XX: "Unspecified"



emotion_mapping:
  NEU: 0
  HAP: 1
  SAD: 2
  ANG: 3
  FEA: 4
  DIS: 5